export const CategoriesArray = [
  {
    id: 1,
    serviceName: 'AC Maintainer',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/bookStore.png'),
  },
  {
    id: 2,
    serviceName: 'Carpenter',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/alnoorStore.png'),
  },
  {
    id: 3,
    serviceName: 'Electrition',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/bookStore.png'),
  },
  {
    id: 4,
    serviceName: 'Painter',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/medicalStore.png'),
  },
  {
    id: 5,
    serviceName: 'Beautician',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/pharmacy.png'),
  },
  {
    id: 6,
    serviceName: 'Plumber',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/store.png'),
  },
  {
    id: 7,
    serviceName: 'Home Appliance',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/cornerStore.png'),
  },
];

export const ServicesArray = [
  {
    id: 1,
    serviceName: 'Service',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/air-conditioner.png'),
  },
  {
    id: 2,
    serviceName: 'Services Providers',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/carpenter.png'),
  },
  {
    id: 3,
    serviceName: 'Booked Requests',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/booking.png'),
  },
  {
    id: 4,
    serviceName: 'Pending Requests',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/booking.png'),
  },
  {
    id: 5,
    serviceName: 'Comlpeted Requests',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/booking.png'),
  },
  {
    id: 6,
    serviceName: 'Cancled Requests',
    name: 'Ijaz',
    desc: 'Your home electrition',
    image: require('../assets/images/booking.png'),
  },
];
